apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: runner
subjects:
- kind: User
  name: runner
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: runner
  apiGroup: rbac.authorization.k8s.io


