apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: runner
rules:
  - apiGroups: ["*"]
    resources: ["ingresses", "services", "deployments", "persistentvolumeclaims"]
    verbs: ["*"]

