apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path-deterministic
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
parameters:
  pathPattern: "{{ .PVC.Namespace }}/{{ .PVC.Name }}"
reclaimPolicy: Retain
