kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ragelberries
provisioner: microk8s.io/hostpath
reclaimPolicy: Retain
parameters:
  pvDir: /mnt/ragelberries
volumeBindingMode: Immediate