apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp
spec:
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - name: testapp-frontend
        image: $CONTAINER_REGISTRY/testapp:e8099367514fdaf8824a5ec57ae246883154dde3
        resources:
          limits:
            memory: "500Mi"
            cpu: "0.25"
      - name: testapp-backend
        image: $CONTAINER_REGISTRY/testapp-api:latest
        env:
          - name: ASPNETCORE_Authentication__Schemes__Bearer__Authority
            value: https://keycloak.ragelberries.net/realms/testrealm
          - name: ASPNETCORE_Authentication__Schemes__Bearer__ValidIssuer
            value: https://keycloak.ragelberries.net/realms/testrealm
          - name: ASPNETCORE_Authentication__Schemes__Bearer__ValidAudiences
            value: testclient
        resources:
          limits:
            memory: "500Mi"
            cpu: "0.25"

---
apiVersion: v1
kind: Service
metadata:
  name: testapp
spec:
  selector:
    app: testapp
  ports:
    - name: testapp-port
      port: 80
      targetPort: 80
    - name: testapp-api-port
      port: 8080
      targetPort: 8080

