apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp
spec:
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - name: testapp-frontend
        image: $CONTAINER_REGISTRY/testapp:67c75d9290f5edf4deb1a4dddfab879baf9fca4e
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
      - name: testapp-backend
        image: $CONTAINER_REGISTRY/testapp-api:latest
        env:
          - name: ASPNETCORE_Authentication__Schemes__Bearer__Authority
            value: https://keycloak.ragelberries.net/realms/testrealm
          - name: ASPNETCORE_Authentication__Schemes__Bearer__ValidIssuer
            value: https://keycloak.ragelberries.net/realms/testrealm
          - name: ASPNETCORE_Authentication__Schemes__Bearer__ValidAudiences
            value: testclient
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: testapp
spec:
  selector:
    app: testapp
  ports:
    - name: testapp-port
      port: 80
      targetPort: 80
    - name: testapp-api-port
      port: 8080
      targetPort: 8080

