apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp
spec:
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - name: vue
        image: ${{CONTAINER_REGISTRY}}/testapp:cd476f4428faff04ee979c4a188d0737d2e2db96
        ports:
---
apiVersion: v1
kind: Service
metadata:
  name: testapp
spec:
  selector:
    app: testapp
  ports:
    - name: http
      port: 80
      targetPort: 8080

