---
- name: Initial tasks and setup
  hosts: all
  become: true
  tasks:
  - name: Update apt-get repo and cache
    ansible.builtin.apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: Upgrade all apt packages
    ansible.builtin.apt: 
      upgrade: dist

  - name: Install packages
    ansible.builtin.apt:
      pkg:
      - rclone
      - restic
      - acl

  - name: Check if /boot/firmware/cmdline.txt exists
    ansible.builtin.stat:
      path: /boot/firmware/cmdline.txt
    register: boot_firmware_cmdline_txt

  - name: Enable cgroup via boot commandline if not already enabled
    ansible.builtin.replace:
      path: "{{ (boot_firmware_cmdline_txt.stat.exists) | ternary('/boot/firmware/cmdline.txt', '/boot/cmdline.txt') }}"
      regexp: '^([\w](?!.*\b{{ cgroup_item }}\b).*)$'
      replace: '\1 {{ cgroup_item }}'
    with_items:
      - "cgroup_enable=cpuset"
      - "cgroup_memory=1"
      - "cgroup_enable=memory"
    loop_control:
      loop_var: cgroup_item

  - name: Create backing storage for kubernetes
    ansible.builtin.file:
      path: /mnt/arvidsson
      state: directory
      mode: '700'

  - name: Reboot to enable cgroup
    ansible.builtin.reboot:
      reboot_timeout: 60

