apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: runner
spec:
  signerName: kubernetes.io/kube-apiserver-client
  groups:
  - system.authenticated
  request: #BASE64 ENCODED CSR#
  usages:
  - digital signature
  - key encipherment
  - client auth
